ProductionTypeBuilding: R
	Description: Building Tab
	Types: Production
	Contexts: Player

ProductionTypeDefense: T
	Description: Defense Tab
	Types: Production
	Contexts: Player

ProductionTypePod: Z
	Description: Pod Tab
	Types: Production
	Contexts: Player

ProductionTypeUtility: K
	Description: Utility Tab
	Types: Production
	Contexts: Player

ProductionTypeTank: U
	Description: Tank Tab
	Types: Production
	Contexts: Player

ProductionTypeAircraft: I
	Description: Aircraft Tab
	Types: Production
	Contexts: Player

ProductionTypeNaval: O
	Description: Naval Tab
	Types: Production
	Contexts: Player

ProductionTypeTrade: P
	Description: Trade Tab
	Types: Production
	Contexts: Player

Production01: Q   
	Types: Production
	Contexts: Player 
Production02: W
	Types: Production
	Contexts: Player
Production03: E
	Types: Production
	Contexts: Player
Production04: A
	Types: Production
	Contexts: Player
Production05: S
	Types: Production
	Contexts: Player
Production06: D
	Types: Production
	Contexts: Player
##### -> only Y for german (and similar) keyboards - international would be Z !
Production07: Y
	Types: Production
	Contexts: Player
Production08: X
	Types: Production
	Contexts: Player
Production09: C
	Types: Production
	Contexts: Player

ToggleVariant: V
	Description: Rotate Building
	Types: Production
	Contexts: Player

PowerDown: KP_2
	Description: Power-down mode
	Types: OrderGenerator
	Contexts: Player
