ProductionTypeBuilding: E
	Description: hotkey-description-production-type-building
	Types: Production
	Contexts: player

ProductionTypeDefense: R
	Description: hotkey-description-production-type-defense
	Types: Production
	Contexts: player

ProductionTypeInfantry: T
	Description: hotkey-description-production-type-infantry
	Types: Production
	Contexts: player

ProductionTypeUtility: K
	Description: hotkey-description-production-type-utility
	Types: Production
	Contexts: player

ProductionTypeVehicle: Y
	Description: hotkey-description-production-type-vehicle
	Types: Production
	Contexts: player

ProductionTypeAircraft: U
	Description: hotkey-description-production-type-aircraft
	Types: Production
	Contexts: player

ProductionTypeNaval: I
	Description: hotkey-description-production-type-naval
	Types: Production
	Contexts: player

ProductionTypeTrade: O
	Description: hotkey-description-production-type-trade
	Types: Production
	Contexts: player

ToggleVariant: V
	Description: hotkey-description-rotate
	Types: Production
	Contexts: player
